variables:
  GOCACHE: "${CI_PROJECT_DIR}/_go/cache"

before_script:
  - mkdir -p ${CI_PROJECT_DIR}/_go/{pkg,bin,cache}
  - rm -rf /go/pkg
  - ln -s ${CI_PROJECT_DIR}/_go/pkg /go/pkg
  - ln -s ${CI_PROJECT_DIR}/_go/bin /go/bin

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - _go
  untracked: true

stages:
  - deps
  - test
  - build

deps:
  stage: deps
  image: golang:1.12
  script:
    - go get -mod=readonly

test:
  stage: test
  dependencies:
    - deps
  image: golang:1.12
  script:
    - find . -name "rice-box.go" -delete
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
    - CGO_ENABLED=1 go test -mod=readonly -race $(go list ./...) -coverprofile .testCoverage.txt

build:
  stage: build
  dependencies:
    - deps
  image: golang:1.12
  script:
    - find . -name "rice-box.go" -delete
    - go get github.com/GeertJohan/go.rice/rice
    - go get github.com/ahmetb/govvv
    - for p in $(go list ./...); do  rice embed-go -i $p; done
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 govvv build -mod=readonly -o release/k8s-go -ldflags '-w -s'
  artifacts:
    paths:
      - release/

